Controllers/AudiosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Api.ccjtv.Controllers
{
    public class AudiosController : Controller
    {
        // GET: Audios
        public ActionResult AgregarAudio()
        {
            return View();
        }
    }
}

Controllers/DiapositivasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Api.ccjtv.Controllers
{
    public class DiapositivasController : Controller
    {
        // GET: Diapositivas
        public ActionResult AgregarDiapositiva()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Api.ccjtv.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Menu()
        {
            return View();
        }

        public ActionResult MenuAudios()
        {
            return View();
        }

        public ActionResult AgregarAudio()
        {
            return View();
        }

        public ActionResult EscucharAudio()
        {
            return View();
        }


        public ActionResult MenuDiapositivas()
        {
            return View();
        }

        public ActionResult MenuImagenes()
        {
            return View();
        }

        public ActionResult MenuVideos()
        {
            return View();
        }
    }
}

Controllers/ImagenesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Api.ccjtv.Controllers
{
    public class ImagenesController : Controller
    {
        // GET: Imagenes
        public ActionResult AgregarImagen()
        {
            return View();
        }
    }
}

Controllers/VideosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Api.ccjtv.Controllers
{
    public class VideosController : Controller
    {
        // GET: Videos
        public ActionResult AgregarVideo()
        {
            return View();
        }
    }
}

Views/Home/Index.cshtml
<!DOCTYPE html>
<html lang="es" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Gartenstadt Schule :: LOGIN</title>
    <!-- FAVICON -->
    <link rel="apple-touch-icon" sizes="57x57" href="~/Imagenes/favicon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="~/Imagenes/favicon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="~/Imagenes/favicon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="~/Imagenes/favicon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="~/Imagenes/favicon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="~/Imagenes/favicon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="~/Imagenes/favicon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="~/Imagenes/favicon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="~/Imagenes/favicon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="~/Imagenes/favicon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/Imagenes/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="~/Imagenes/favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/Imagenes/favicon/favicon-16x16.png">
    <link rel="manifest" href="~/Imagenes/favicon/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="~/Imagenes/favicon/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="~/css/main.css">

</head>
<body>
    <section id="navbar">
        <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top py-0">
            <a class="navbar-brand" href="http://ccj.switchit.com.ar/index.html"><img class="img-brand" src="~/Imagenes/logo-01.png" alt="logo Gartenstadt Schule"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <ul class="navbar-nav ml-auto border-right">
                    <li class="nav-item active">
                        <a class="nav-link" href="http://ccj.switchit.com.ar/index.html">Colegio Ciudad Jardin</a>
                    </li>
                </ul>
                <img class="img-lang" src="~/Imagenes/iconos-13.png" alt="">
            </div>
        </nav>
    </section>

    <section id="data">
        <div id="login">
            <div class="container p-5">
                <div id="login-row" class="row justify-content-center align-items-center">
                    <div id="login-column" class="col-md-12">
                        <div id="login-box" class="col-md-12">
                            <form id="login-form" class="form" action="" method="post">
                                <h3 class="text-center text-info">Iniciar Sesión</h3>
                                <div class="form-group">
                                    <label for="username" class="text-info">Usuario:</label><br>
                                    <input type="text" name="username" id="username" class="form-control">
                                </div>
                                <div class="form-group">
                                    <label for="password" class="text-info">Contraseña:</label><br>
                                    <input type="password" name="password" id="password" class="form-control">
                                </div>
                                <div class="form-group">   
                                    <input type="button" class="btn btn-info btn-block" onclick ="LoguearUsuario()" value="Ingresar" />
                                    <div class="error-logueo col-md-12">
                                        <span id="ErrorLogueo"></span>                                        
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
       
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="~/Js/Loguear.js" ></script>
</body>
</html>

Views/Home/Menu.cshtml
<!DOCTYPE html>
<html lang="es" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Gartenstadt Schule</title>
    <!-- FAVICON -->
    <link rel="apple-touch-icon" sizes="57x57" href="~/Imagenes/favicon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="~/Imagenes/favicon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="~/Imagenes/favicon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="~/Imagenes/favicon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="~/Imagenes/favicon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href=".~/Imagenes/favicon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="~/Imagenes/favicon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="~/Imagenes/favicon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="~/Imagenes/favicon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="~/Imagenes/favicon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/Imagenes/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="~/Imagenes/favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/Imagenes/favicon/favicon-16x16.png">
    <link rel="manifest" href="~/Imagenes/favicon/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="~/Imagenes/favicon/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/main.css">
</head>
<body>
    <section id="navbar" style="height:20px;">
        <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top py-0">
            <a class="navbar-brand" href="http://ccj.switchit.com.ar/index.html"><img class="img-brand" src="~/Imagenes/logo-01.png" alt="logo Gartenstadt Schule"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="dropdown show">
                    <a class="btn btn-light add-btn dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <svg class="bi bi-cloud-upload" width="1.5rem" height="1.5rem" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path d="M6.887 8.2l-.964-.165A2.5 2.5 0 105.5 13H8v1H5.5a3.5 3.5 0 11.59-6.95 5.002 5.002 0 119.804 1.98A2.501 2.501 0 0115.5 14H12v-1h3.5a1.5 1.5 0 00.237-2.982L14.7 9.854l.216-1.028a4 4 0 10-7.843-1.587l-.185.96z"></path>
                            <path fill-rule="evenodd" d="M7 10.854a.5.5 0 00.707 0L10 8.56l2.293 2.293a.5.5 0 00.707-.707L10.354 7.5a.5.5 0 00-.708 0L7 10.146a.5.5 0 000 .708z" clip-rule="evenodd"></path>
                            <path fill-rule="evenodd" d="M10 8a.5.5 0 01.5.5v8a.5.5 0 01-1 0v-8A.5.5 0 0110 8z" clip-rule="evenodd"></path>
                        </svg>
                        Cargar
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item" href="@Url.Action("AgregarAudio", "Audios")">Audio</a>
                        <a class="dropdown-item" href="@Url.Action("AgregarVideo", "Videos")">Video</a>
                        <a class="dropdown-item" href="@Url.Action("AgregarDiapositiva", "Diapositivas")">Diapositiva</a>
                        <a class="dropdown-item" href="@Url.Action("AgregarImagen", "Imagenes")">Imagen</a>
                    </div>
                </div>
                <ul class="navbar-nav ml-auto border-right">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Home")">INICIAR SESIÓN / CERRAR SESIÓN</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Colegio Ciudad Jardin <span class="sr-only">(current)</span></a>
                    </li>
                </ul>
                <img class="img-lang" src="~/Imagenes/iconos-13.png" alt="">
            </div>
        </nav>
    </section>

    <section id="niveles" class="container-fluid pt-5">
        <div class="mt-5">
            <div class="row">
                <div class="col">
                    <a  href="@Url.Action("MenuAudios", "Home")">
                        <div class="cuadro">
                            <img class="icono" src="~/Imagenes/iconos-01.png" alt="">
                            <h1>AUDIOS</h1>
                        </div>
                    </a>
                </div>
                <div class="col">
                    <a  href="@Url.Action("MenuImagenes", "Home")">
                        <div class="cuadro">
                            <img class="icono" src="~/Imagenes/iconos-02.png" alt="">
                            <h1>IMAGENES</h1>
                        </div>
                    </a>
                </div>
                <div class="col">
                    <a  href="@Url.Action("MenuVideos", "Home")">
                        <div class="cuadro">
                            <img class="icono" src="~/Imagenes/iconos-03.png" alt="">
                            <h1>VIDEOS</h1>
                        </div>
                    </a>
                </div>
                <div class="col">
                    <a  href="@Url.Action("MenuDiapositivas", "Home")">
                        <div class="cuadro">
                            <img class="icono" src="~/Imagenes/iconos-04.png" alt="">
                            <h1>DIAPOSITIVAS</h1>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </section>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

Views/Home/MenuAudios.cshtml
<!DOCTYPE html>
<html lang="es" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>CCJTV : Audios</title>
    <!-- FAVICON -->
    <link rel="apple-touch-icon" sizes="57x57" href="~/Imagenes/favicon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="~/Imagenes/favicon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="~/Imagenes/favicon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="~/Imagenes/favicon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="~/Imagenes/favicon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="~/Imagenes/favicon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="~/Imagenes/favicon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="~/Imagenes/favicon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="~/Imagenes/favicon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="~/Imagenes/favicon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/Imagenes/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="~/Imagenes/favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/Imagenes/favicon/favicon-16x16.png">
    <link rel="manifest" href="~/Imagenes/favicon/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="~/Imagenes/favicon/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/main.css">
</head>
<body>
    <section id="navbar" style="height:20px;">
        <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top py-0">
            <a class="navbar-brand" href="http://ccj.switchit.com.ar/index.html"><img class="img-brand" src="~/Imagenes/logo-01.png" alt="logo Gartenstadt Schule"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="dropdown show">
                    <a class="btn btn-light add-btn dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <svg class="bi bi-cloud-upload" width="1.5rem" height="1.5rem" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path d="M6.887 8.2l-.964-.165A2.5 2.5 0 105.5 13H8v1H5.5a3.5 3.5 0 11.59-6.95 5.002 5.002 0 119.804 1.98A2.501 2.501 0 0115.5 14H12v-1h3.5a1.5 1.5 0 00.237-2.982L14.7 9.854l.216-1.028a4 4 0 10-7.843-1.587l-.185.96z"></path>
                            <path fill-rule="evenodd" d="M7 10.854a.5.5 0 00.707 0L10 8.56l2.293 2.293a.5.5 0 00.707-.707L10.354 7.5a.5.5 0 00-.708 0L7 10.146a.5.5 0 000 .708z" clip-rule="evenodd"></path>
                            <path fill-rule="evenodd" d="M10 8a.5.5 0 01.5.5v8a.5.5 0 01-1 0v-8A.5.5 0 0110 8z" clip-rule="evenodd"></path>
                        </svg>
                        Cargar
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item" href="@Url.Action("AgregarAudio", "Audios")">Audio</a>
                        <a class="dropdown-item" href="@Url.Action("AgregarVideo", "Videos")">Video</a>
                        <a class="dropdown-item" href="@Url.Action("AgregarDiapositiva", "Diapositivas")">Diapositiva</a>
                        <a class="dropdown-item" href="@Url.Action("AgregarImagen", "Imagenes")">Imagen</a>
                    </div>
                </div>
            </div>
            <ul class="navbar-nav ml-auto border-right">
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Home")">INICIAR SESIÓN / CERRAR SESIÓN</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="#">Colegio Ciudad Jardin <span class="sr-only">(current)</span></a>
                </li>
            </ul>
            <img class="img-lang" src="~/Imagenes/iconos-13.png" alt="">
        </nav>
    </section>

    <section id="menu" class="mt-5">
        <div class="btn-group ml-5 my-4">
            <button class="btn btn-danger dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                AUDIOS
            </button>
            <div class="dropdown-menu">
                @*<a class="dropdown-item" href="@Url.Action("MenuAudios", "Home")">Audios</a>*@ 
                <a class="dropdown-item" href="@Url.Action("MenuVideos", "Home")">Videos</a>
                <a class="dropdown-item" href="@Url.Action("MenuDiapositivas", "Home")">Diapositivas</a>
                <a class="dropdown-item" href="@Url.Action("MenuImagenes", "Home")">Imagenes</a>
            </div>
        </div>
        <div class="px-5">
            <ul class="list-unstyled row">
                <li class="col-lg-2 col-sm-2 col-xs-2 p-3">
                    <a href="videos/album-name.html">
                        <img src="~/Imagenes/aleman.jpg" alt="logo" class="img-fluid album" />
                        <p>Nombre del album o Carpeta contenedora</p>
                    </a>
                </li>
                <li class="col-lg-2 col-sm-2 col-xs-2 p-3">
                    <a href="videos/album-name.html">
                        <img src="~/Imagenes/logo.png" alt="logo" class="img-fluid album" />
                        <p>Nombre del album o Carpeta contenedora</p>
                    </a>
                </li>
                <li class="col-lg-2 col-sm-2 col-xs-2 p-3">
                    <a href="videos/album-name.html">
                        <img src="~/Imagenes/logo.png" alt="logo" class="img-fluid album" />
                        <p>Nombre del album o Carpeta contenedora</p>
                    </a>
                </li>
                <li class="col-lg-2 col-sm-2 col-xs-2 p-3">
                    <a href="videos/album-name.html">
                        <img src="~/Imagenes/logo.png" alt="logo" class="img-fluid album" />
                        <p>Nombre del album o Carpeta contenedora</p>
                    </a>
                </li>
                <li class="col-lg-2 col-sm-2 col-xs-2 p-3">
                    <a href="videos/album-name.html">
                        <img src="~/Imagenes/logo.png" alt="logo" class="img-fluid album" />
                        <p>Nombre del album o Carpeta contenedora</p>
                    </a>
                </li>
                <li class="col-lg-2 col-sm-2 col-xs-2 p-3">
                    <a href="videos/album-name.html">
                        <img src="~/Imagenes/logo-01.png" alt="logo" class="img-fluid album" />
                        <p>Nombre del album o Carpeta contenedora</p>
                    </a>
                </li>
                <li class="col-lg-2 col-sm-2 col-xs-2 p-3">
                    <a href="videos/album-name.html">
                        <img src="~/Imagenes/logo.png" alt="logo" class="img-fluid album" />
                        <p>Nombre del album o Carpeta contenedora</p>
                    </a>
                </li>
                <li class="col-lg-2 col-sm-2 col-xs-2 p-3">
                    <a href="videos/album-name.html">
                        <img src="~/Imagenes/logo.png" alt="logo" class="img-fluid album" />
                        <p>Nombre del album o Carpeta contenedora</p>
                    </a>
                </li>
            </ul>
        </div>
    </section>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>